version: '3.8' # Versão do Docker Compose
services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: go_db # Banco de dados
      MYSQL_USER: go_user # Usuário do banco de dados
      MYSQL_PASSWORD: go_pass # Senha do banco de dados
      MYSQL_ROOT_PASSWORD: go_root_pass # Senha root do banco de dados
    ports:
      - 8306:3306 # Portal local e porta do docker
    volumes:
      - ./data:/var/lib/mysql
